version: '3'

services:
  api:
    build: ./server
    ports:
      - 5000:3000 
    env_file:
      - ./server/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_PASSWORD: password
      DB_USER: postgres
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - 80:80
    volumes:
      - ./client/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./server/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./server/sql/fill_tables.sql:/docker-entrypoint-intidb.d/fill_tables.sql

# volumes:
#   db: